name: checks
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking-Out Code
        uses: actions/checkout@v2
      - name: Installing Dependencies
        run: npm install
      - name: Linting Code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking-Out Code
        uses: actions/checkout@v2
      - name: Installing Dependencies
        run: npm install
      - name: Running Unit Tests
        run: npm test
